Date news card
Baltimore-County-Government/dotgov-components pull request #115
Opened 2019-09-12 13:11 UTC by martypowell

Addresses #109

2019-09-12 13:11 UTC, martypowell commented
I didn't add a test file or usage for the component, adding now.

2019-09-12 13:18 UTC, sdurphy commented
it looks like at around 600px screen width, .dg_date-news-card__headline sticks out of the container... screenshot attached.
![Screen Shot 2019-09-12 at 9 18 16 AM](https://user-images.githubusercontent.com/2189638/64787219-4000e580-d53e-11e9-8dfe-8f588e2b5e88.png)

2019-09-12 13:37 UTC, sdurphy requested changes
it looks like at around 600px screen width, .dg_date-news-card__headline sticks out of the container.

2019-09-12 13:40 UTC, martypowell commented
Added tests, adding html next.

2019-09-12 13:43 UTC, martypowell commented
added snippets. @danfox01 @jdomasky @sdurphy  this is ready for testing. This component includes all states right now, but once this is confirmed, I think we should remove the state examples in favor of just showing a default and dark example.

What do you guys think?

2019-09-12 13:44 UTC, danfox01 commented
> added snippets. @danfox01 @jdomasky @sdurphy this is ready for testing. This component includes all states right now, but once this is confirmed, I think we should remove the state examples in favor of just showing a default and dark example.
> 
> What do you guys think?

@martypowell agreed.

@jdomasky can you please test? Let me know if you need links/additional info.

2019-09-12 13:45 UTC, martypowell commented
> it looks like at around 600px screen width, .dg_date-news-card__headline sticks out of the container... screenshot attached.
> ![Screen Shot 2019-09-12 at 9 18 16 AM](https://user-images.githubusercontent.com/2189638/64787219-4000e580-d53e-11e9-8dfe-8f588e2b5e88.png)

@sdurphy this is a result of the system layout, not the comopnet, see this screenshot, where i removed the sidebar:

![image](https://user-images.githubusercontent.com/1933400/64789230-ffa36680-d541-11e9-8114-915337c49514.png)

2019-09-12 13:50 UTC, jdomasky commented
@danfox01 @martypowell I'll begin testing for this component shortly.

2019-09-12 13:54 UTC, martypowell commented
@danfox01 i think maybe i got the markup wrong here, and it should be an [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article)? 

Also thinking for the date, maybe we need a screen-reader veriosn, since our date is decoration-y?

2019-09-12 14:01 UTC, danfox01 commented
@martypowell `<article> `seems like it would make most sense. I'm not sure about the accessibility on this one. We can look into it.

Are you pushing more changes or is @jdomasky good to test?

2019-09-12 14:02 UTC, martypowell commented
> @martypowell
> 
> seems like it would make most sense. I'm not sure about the accessibility on this one. We can look into it.
> Are you pushing more changes or is @jdomasky good to test?

We can test. @danfox01 @jdomasky

2019-09-12 14:17 UTC, jdomasky commented
@martypowell @danfox01 Testing is underway.

2019-09-12 15:33 UTC, theilman7 commented on src/components/basic/DateNewsCard.md
> +<div style={{ padding: '10px'}} className="dg_section">
Can the inline style included here be migrated to the style sheet? Disregard if this was setup for display purposes only.

2019-09-12 16:26 UTC, jdomasky commented
@martypowell @sdurphy First round of testing is finished. Emailing results to @danfox01.

2019-09-12 17:24 UTC, martypowell commented on src/components/basic/DateNewsCard.md
> +<div style={{ padding: '10px'}} className="dg_section">
display purposes only @theilman7 but i do think that once we addressed the styles sheet styles, this should be addressed.

2019-09-12 18:42 UTC, danfox01 commented
Test results per @jdomasky, and triaged by @sdurphy and @martypowell:

- Disabled on dark background is incorrect.
- Month abbreviation in date should be call caps.
- Article headline should be title case.
- Spacing between date and headline needs to be adjusted to match mockup.
- Adjust padding around snippet to match mockup.
- Border separator above teaser should be 1px, not 2px.
- Border peparator position should be centered vertically between tghe elements above and below. (Padding fix will probably correct this.)
- Border color in hovered and disabled states should be `white`, not `gray-light`.

2019-09-12 18:52 UTC, martypowell commented
> Test results per @jdomasky, and triaged by @sdurphy and @martypowell:
> 
> * Disabled on dark background is incorrect.
> * Month abbreviation in date should be call caps.
> * Article headline should be title case.
> * Spacing between date and headline needs to be adjusted to match mockup.
> * Adjust padding around snippet to match mockup.
> * Border separator above teaser should be 1px, not 2px.
> * Border peparator position should be centered vertically between tghe elements above and below. (Padding fix will probably correct this.)
> * Border color in hovered and disabled states should be `white`, not `gray-light`.

@danfox01 addressed.

@jdomasky ready for another look. Any of the spacing issues should be in 5px increments, and may be slightly different than the xd document.

2019-09-12 18:57 UTC, jdomasky commented
@martypowell @danfox01 Update: Reviewing now.

2019-09-12 19:34 UTC, jdomasky commented
@martypowell @danfox01 All of the testing issues have been resolved. This component is good to go.

2019-09-13 00:53 UTC, martypowell commented
@danfox01 @sdurphy this is ready for a rubber stamp. I removed the state examples as we talked about earlier today.

2019-09-13 01:08 UTC, danfox01 approved these changes
Stamp

2019-09-13 01:19 UTC, merged