Added IE hack style for focus.
Baltimore-County-Government/dotgov-components pull request #186
Opened 2019-10-24 13:35 UTC by tmccoy529

Added new IE hack to fix focus issues.

2019-10-24 13:54 UTC, martypowell approved these changes

2019-10-24 13:55 UTC, martypowell requested changes
@tmccoy529 the ms-focus-within needs to go inside the media query in ie-hacks

2019-10-24 13:57 UTC, martypowell commented on src/styles/overrides/_ie-hacks.scss
> +.ms-focus-within {
This needs to move into the media query, otherwise it will be available in all browsers.

2019-10-24 16:28 UTC, martypowell submitted a review, later dismissed
Looks good

2019-10-24 18:14 UTC, tmccoy529 commented
@martypowell the class was moved inside of the media query

2019-10-25 12:46 UTC, martypowell commented
@tmccoy529 can you bump the version number in the package.json file for this, and then merge this pull request so i can push up to npm?

2019-10-25 17:59 UTC, martypowell approved these changes

2019-10-25 17:59 UTC, merged

2019-10-25 18:00 UTC, martypowell commented
@tmccoy529 merged on behalf you so, so we can get this up to npm.