Buttons
Baltimore-County-Government/dotgov-components pull request #89
Opened 2019-08-26 12:49 UTC by martypowell

Addresses #37 

- Primary Buttons
- Secondary Buttons
- Link Buttons
- Icon Links

Adds animation to hover for buttons and links.

Does not add navigation buttons, that will be handled as part of the navigation build

2019-08-26 13:12 UTC, martypowell commented
@martypowell please add examples for the button usage to the docs.

2019-08-26 14:15 UTC, martypowell commented on src/styles/partials/components/_button.scss
> +	&:active,
these can be simlified a bit.

2019-08-26 14:37 UTC, martypowell commented on src/styles/partials/components/_button.scss
> +	&:active,
simplified as much as possible

2019-08-26 14:38 UTC, martypowell commented on src/components/basic/IconLink.js
> +	const sizes = {
we should probably just control this through a class, in order to simplify this. Be sure to update the docs.

2019-08-26 15:14 UTC, martypowell commented on src/components/basic/IconLink.js
> +	const sizes = {
this is done.

2019-08-26 15:16 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +	&.dg_icon-link--small {
this looks like a good case for a mixin

2019-08-26 15:16 UTC, danfox01 requested changes
@martypowell looks great, except for a few things:

- Hover state of `dg_button-link` in a dark section is incorrect. The background color should not change on hover, instead the link color should change.
- Font weight of `dg_button-link` should be 600 (semibold) not 700 (bold)
- I noticed we're not currently pulling the italic version of Crimson. We need to add this for true italics.

FYI @sdurphy

2019-08-26 15:21 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +	&.dg_icon-link--small {
done in latest changes.

2019-08-26 17:35 UTC, martypowell commented
> @martypowell looks great, except for a few things:
> 
> * Hover state of `dg_button-link` in a dark section is incorrect. The background color should not change on hover, instead the link color should change.
> * Font weight of `dg_button-link` should be 600 (semibold) not 700 (bold)
> * I noticed we're not currently pulling the italic version of Crimson. We need to add this for true italics.
> 
> FYI @sdurphy

Hey @sdurphy @danfox01 did these get addressed?

2019-08-26 19:42 UTC, danfox01 commented
Per testing by @jdomasky, a few inconsistencies and variation from the comps:

- For `dg_icon-link` in a dark section, the hover color should be `blue-lightest` not `blue-vibrant`.
- Most of the active state examples also respond to hover. The exception seems to be `dg_icon-link` and `dg_icon-link--small`, which do not show a hover state. Seems weird to me that an example of an active state would have a hover, so I'm not sure which approach is correct. For reference, the [active button examples in the USDS style guid](https://designsystem.digital.gov/components/button/)e do not respond to hover. Regardless, our examples should be consistent.

It's also worth noting that the buttons sizes may need to be tweaked for mobile in future iterations. This might be related to responsive typography.

2019-08-26 20:13 UTC, theilman7 commented on src/styles/partials/components/_link.scss
> +		line-height: 100px;
This is more of a question. I'm wondering if we should include values for line-height and other CSS typographic focused variables in the _fonts.scss file. IE. $line-height-lg, $line-height-sm etc.

2019-08-26 20:15 UTC, theilman7 commented on src/styles/partials/base/_button-reset.scss
> +
For consistency and for cleaning up the markup, I would add the background property before border so we can maintain the alphabetic order of css properties.

2019-08-26 20:20 UTC, theilman7 commented on src/styles/partials/components/_button.scss
> +
For consistency, move the border-color property below the background property.

2019-08-26 20:22 UTC, theilman7 commented on src/styles/partials/components/_label.scss
These properties should be in the following order for consistency: font-size, font-weight, margin-top.

2019-08-27 12:06 UTC, martypowell commented on src/styles/partials/base/_button-reset.scss
> +
i copied this from somewhere, else, but I'm good wtih this comment.

2019-08-27 12:08 UTC, martypowell commented on src/styles/partials/components/_button.scss
> +
good catch, done.

2019-08-27 12:08 UTC, martypowell commented on src/styles/partials/components/_label.scss
adjusted.

2019-08-27 12:10 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +		line-height: 100px;
I don't have a strong knowledge of how to effectively use line height, it's always more have been a case by case basis for me personally. If i you have a good handle on this, then I'd defer to you. But I'm always in favor of creating some more rules around this.

2019-08-27 12:12 UTC, martypowell commented on src/styles/partials/base/_button-reset.scss
> +
adjusted any no commented proprties

2019-08-27 12:14 UTC, martypowell commented
> Per testing by @jdomasky, a few inconsistencies and variation from the comps:
> 
> * For `dg_icon-link` in a dark section, the hover color should be `blue-lightest` not `blue-vibrant`.
> * Most of the active state examples also respond to hover. The exception seems to be `dg_icon-link` and `dg_icon-link--small`, which do not show a hover state. Seems weird to me that an example of an active state would have a hover, so I'm not sure which approach is correct. For reference, the [active button examples in the USDS style guid](https://designsystem.digital.gov/components/button/)e do not respond to hover. Regardless, our examples should be consistent.
> 
> It's also worth noting that the buttons sizes may need to be tweaked for mobile in future iterations. This might be related to responsive typography.

Looking now. I also think i got the clasess wrong, looking now. Since doing this pr I realized I should have done one button set a time :disappointed:

2019-08-27 12:21 UTC, martypowell commented
> > Per testing by @jdomasky, a few inconsistencies and variation from the comps:
> > 
> > * For `dg_icon-link` in a dark section, the hover color should be `blue-lightest` not `blue-vibrant`.
> > * Most of the active state examples also respond to hover. The exception seems to be `dg_icon-link` and `dg_icon-link--small`, which do not show a hover state. Seems weird to me that an example of an active state would have a hover, so I'm not sure which approach is correct. For reference, the [active button examples in the USDS style guid](https://designsystem.digital.gov/components/button/)e do not respond to hover. Regardless, our examples should be consistent.
> > 
> > It's also worth noting that the buttons sizes may need to be tweaked for mobile in future iterations. This might be related to responsive typography.
> 
> Looking now. I also think i got the classess wrong, looking now. Since doing this pr I realized I should have done one button set a time :/

@danfox01 I think all issues have been addressed, please review.

2019-08-27 14:06 UTC, danfox01 commented
Per conversation with @martypowell final review of this issue is on hold until later this week. When we resume, here are retest results from @jdomasky:

> 1. The hover class was removed from all of the Active buttons except for one: Text Button in a Dark Section.
> 2. In the Decorative Links in a Dark Section (both Large and Small), the Disabled buttons have a hover class configured. I believe this is a new bug. I don't remember observing hover on these buttons when we tested yesterday.

2019-08-27 19:30 UTC, martypowell commented
> Per conversation with @martypowell final review of this issue is on hold until later this week. When we resume, here are retest results from @jdomasky:
> 
> > 1. The hover class was removed from all of the Active buttons except for one: Text Button in a Dark Section.
> > 2. In the Decorative Links in a Dark Section (both Large and Small), the Disabled buttons have a hover class configured. I believe this is a new bug. I don't remember observing hover on these buttons when we tested yesterday.

Both valid bugs and addressed @jdomasky ready for another look.

fyi @danfox01

2019-08-27 19:32 UTC, jdomasky commented
@martypowell @danfox1 Taking another look.

2019-08-27 19:42 UTC, jdomasky commented
@martypowell @danfox1 The issues in the retest results from this morning have been resolved. However, there's still an issue with this component:

- In the Secondary Button set and the Text Button in a Dark Section, the Disabled buttons have a hover class configured. I'm not sure if this was overlooked during retesting or if this issue was just introduced.
**Recommendation:** Remove the hover class from these two Disabled buttons.

2019-08-28 11:52 UTC, martypowell commented
> @martypowell @danfox1 The issues in the retest results from this morning have been resolved. However, there's still an issue with this component:
> 
> * In the Secondary Button set and the Text Button in a Dark Section, the Disabled buttons have a hover class configured. I'm not sure if this was overlooked during retesting or if this issue was just introduced.
>   **Recommendation:** Remove the hover class from these two Disabled buttons.

@jdomasky this is a bug, and was just overlooked, fixing now.

2019-08-28 12:09 UTC, martypowell commented on src/styles/partials/components/_button.scss
> +
@theilman7 ready for another look

2019-08-28 12:10 UTC, martypowell commented on src/styles/partials/components/_label.scss
@theilman7 ready for another look

2019-08-28 12:10 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +		line-height: 100px;
> > @martypowell @danfox1 The issues in the retest results from this morning have been resolved. However, there's still an issue with this component:
> > 
> > * In the Secondary Button set and the Text Button in a Dark Section, the Disabled buttons have a hover class configured. I'm not sure if this was overlooked during retesting or if this issue was just introduced.
> >   **Recommendation:** Remove the hover class from these two Disabled buttons.
> 
> @jdomasky this is a bug, and was just overlooked, fixing now.

@jdomasky this is ready for another look.

2019-08-28 13:47 UTC, danfox01 commented
@martypowell , this is good to merge.

2019-08-28 13:52 UTC, jdomasky commented on src/styles/partials/components/_link.scss
> +		line-height: 100px;
@martypowell The buttons are good to go. All testing issues have been resolved.

2019-08-28 14:08 UTC, merged