Icon button#13
Baltimore-County-Government/dotgov-components pull request #95
Opened 2019-08-28 18:44 UTC by sgrg1

worked on existing IconLink.js file . added navigation link.

2019-08-28 18:48 UTC, martypowell commented on src/components/basic/IconLink.js
> +	const { icon, href, description, size = defaultSize, text, className, ...rest } = props;
so href is already handled by `...rest` but i don't mind specifying it explicitly. If you look at the prop types its required.

2019-08-28 18:50 UTC, martypowell commented on src/components/basic/IconLink.js
> +	const navigationLink = href ? href:`javascript:void(0);`;
We do not need the check for if the href exist, its always required.

2019-08-28 18:52 UTC, martypowell requested changes
I don't see any css/sass changes in this pr. Did you take a look at the mockup in issue #13

2019-08-30 11:33 UTC, martypowell commented on src/components/basic/IconButton.md
> +<div class="dg_form-field">
this markup doesn't match the components output.

2019-08-30 11:34 UTC, martypowell commented on src/components/basic/IconButton.md
> +text="TRASH AND RECYCLING SCHEDULE"
This text should be use regular casing, the css will handle the uppercase piece, this offers us the flexabilty to change the way it's displayed.

2019-08-30 11:35 UTC, martypowell commented on src/components/basic/IconButton.md
> +description="Show Icon"
this is unclear.

2019-08-30 11:36 UTC, martypowell commented on src/styles/partials/components/_input.scss
>  	border: $input-border-width solid $black;
not sure how this built, without the variable declaration.

2019-08-30 11:36 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +
please remove this space.

2019-08-30 11:37 UTC, martypowell commented on src/styles/partials/components/_icon-button.scss
> +.dg_icon-buttonDefault {
the class should be {namespace}_{component}--{modifier} so in this case, `.dg_icon-button--default`

2019-08-30 11:38 UTC, martypowell commented on src/styles/partials/components/_icon-button.scss
> +	transition: all 0.3s ease 0s;
transition is handled at a global level

2019-08-30 11:38 UTC, martypowell commented on src/styles/partials/components/_icon-button.scss
> +	svg {
not sure where the svg is coming from here, we aren't using svg's that i know of.

2019-08-30 11:39 UTC, martypowell commented on src/styles/partials/components/_icon-button.scss
> +.dg_icon-buttonAlternative {
same as above:

the class should be {namespace}_{component}--{modifier} so in this case, .`dg_icon-button--alternate`

2019-08-30 11:40 UTC, martypowell commented on src/styles/partials/components/_icon-button.scss
> +	color: $white;
a lot of this is repeated, you should be able to do

```css
.dg_icon-button {
  // shared styles go here
}

.dg_icon-button--default {
  // styles that only apply to default
}

.dg_icon-button--alternative {
  // styles that only apply to default
}
```

2019-08-30 11:41 UTC, martypowell commented on src/styles/partials/components/_icon-button.scss
> +	color: $white;
your component would then have, dg_icon-button and dg_icon-button--modifier clasess

2019-08-30 11:41 UTC, martypowell requested changes
Since @sgrg1 is out, i am going to address the comments.

2019-08-30 11:52 UTC, martypowell commented on src/styles/partials/components/_input.scss
>  	border: $input-border-width solid $black;
this worked, because boostrap had the variable declared, changed to use our default border.

2019-08-30 14:41 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +		i {
some of these rules can be combined.

2019-08-30 14:42 UTC, martypowell reviewed
please combine the css when you can.

2019-08-30 14:44 UTC, martypowell commented on src/styles/partials/components/_link.scss
> +		i {
combined.

2019-08-30 14:45 UTC, martypowell commented
@danfox01 @jdomasky this is ready for a look. Please restest `Decorative Links` 

![image](https://user-images.githubusercontent.com/1933400/64029783-43927680-cb13-11e9-8944-a482672f1d2e.png)


as well, the markup for each components is shared, and only differs in style.

2019-08-30 15:19 UTC, danfox01 commented
Not sure about this name of this, but we can adjust later. @martypowell, this is good to go.

2019-08-30 15:29 UTC, martypowell commented
> Not sure about this name of this, but we can adjust later. @martypowell, this is good to go.

Would be a good time to change it, if you want. I went quite literal here.

2019-08-30 15:33 UTC, danfox01 commented
Card button
[http://www.baltimorecountymd.gov/sebin/v/b/census-logo.png]<http://www.baltimorecountymd.gov>



Connect with Baltimore County


[http://www.baltimorecountymd.gov/sebin/x/g/social-icon-facebook.png]<https://www.facebook.com/baltcogov>       [http://www.baltimorecountymd.gov/sebin/p/o/social-icon-twitter.png] <https://twitter.com/BaltCoGov>    [http://www.baltimorecountymd.gov/sebin/z/n/social-icon-news.png] <http://www.baltimorecountymd.gov/News/BaltimoreCountyNow>    [http://www.baltimorecountymd.gov/sebin/b/d/social-icon-youtube.png] <https://www.youtube.com/user/BaltimoreCounty>     [http://www.baltimorecountymd.gov/sebin/l/y/social-icon-flickr.png] <https://www.flickr.com/photos/baltimorecounty>     [http://www.baltimorecountymd.gov/sebin/t/q/social-icon-linkedin.png] <https://www.linkedin.com/company/baltimore-county-government>

www.baltimorecountymd.gov<http://www.baltimorecountymd.gov>

2019-08-30 15:36 UTC, martypowell commented
> Card button [[http://www.baltimorecountymd.gov/sebin/v/b/census-logo.png]<http://www.baltimorecountymd.gov](http://www.baltimorecountymd.gov/sebin/v/b/census-logo.png%5D<http://www.baltimorecountymd.gov)> Connect with Baltimore County [[http://www.baltimorecountymd.gov/sebin/x/g/social-icon-facebook.png]<https://www.facebook.com/baltcogov](http://www.baltimorecountymd.gov/sebin/x/g/social-icon-facebook.png%5D<https://www.facebook.com/baltcogov)> [http://www.baltimorecountymd.gov/sebin/p/o/social-icon-twitter.png] <https://twitter.com/BaltCoGov> [http://www.baltimorecountymd.gov/sebin/z/n/social-icon-news.png] <http://www.baltimorecountymd.gov/News/BaltimoreCountyNow> [http://www.baltimorecountymd.gov/sebin/b/d/social-icon-youtube.png] <https://www.youtube.com/user/BaltimoreCounty> [http://www.baltimorecountymd.gov/sebin/l/y/social-icon-flickr.png] <https://www.flickr.com/photos/baltimorecounty> [http://www.baltimorecountymd.gov/sebin/t/q/social-icon-linkedin.png] <https://www.linkedin.com/company/baltimore-county-government> [www.baltimorecountymd.gov<http://www.baltimorecountymd.gov](http://www.baltimorecountymd.gov<http://www.baltimorecountymd.gov)>

I'm afraid of using Button when its not a button. It seems like semantics, but it's a very different thing.

2019-08-30 17:08 UTC, martypowell commented
going to copmlete for now, since we didn't come to a conclusion.

2019-08-30 17:09 UTC, martypowell commented
> going to copmlete for now, since we didn't come to a conclusion.

will be addressed in the near future (probably next sprint)

2019-08-30 17:09 UTC, merged